pref("extensions.bitTorrentWebUI.serverScheme",	"https://");
pref("extensions.bitTorrentWebUI.dispatcher", 	"AzureusDispatcher");
pref("extensions.bitTorrentWebUI.firstRun", 	true);
pref("extensions.bitTorrentWebUI.enabled",		true);
pref("extensions.bitTorrentWebUI.debugToConsole",	false);
pref("extensions.bitTorrentWebUI.serverAddress", 	"");
pref("extensions.bitTorrentWebUI.serverUsername",	"");
pref("extensions.bitTorrentWebUI.showStatusIcon", 	true);
pref("extensions.bitTorrentWebUI.beepEnabled", 	true);
